apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:iDL3ZPJfK0L+LTQ=,iv:Hc6+pnAV411F7f9hkoY9zt0jBx7SDXv7U36CV3nXRdo=,tag:WvJURzvXGlURMFSIgJfJjg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:8IEo5pWG03PXCZiKRp+RdXNs2L2Ld8ZZIx31x271ubOqmnNFHA==,iv:xTFk2PGfEJfeghZ4crOE4WieeGElvfjQozu3k7GNBTw=,tag:i4eyVJX43iwG/U5kLpNuHw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:uFtKdud9hPwsRC8j5oJujw==,iv:h9SDs4glUwhL4taFIIdukEttxXkzWft2FrXfkpiqPAg=,tag:j2/T0Qdn1v52PcHFmxI1TA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15f0yq8uvrva2hpd6grn489knhvkarj6g9xfdgyrh8mdajuq53q2q4a3uq3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraFFjTHZnQmFPcDdBMTd3
            Tk1TOHNxWnBSd2h3Q1pGMVp4YUwyNmZOUUNRCnFLcE1wdmFSeXo4WElkME9yS3Bo
            S1VpSWJ1OWtQcmdNaS95ZnU0OUNHcUkKLS0tIC9JK2pCR2F3NHpRV2Q3MGpjZ3cw
            ZnpiSU1nU2F0RjRJNDdPWnNSUzVuU3MKB3PZfmcEHYohOI6rbNZawlGBb/yaqp+F
            eeVeRzrK7LVsw4wR5Z7Ph3kJuM1bLIOER9W3aStTV1CZY+YDRS0rSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-16T09:48:36Z"
    mac: ENC[AES256_GCM,data:zLa0kmcKkfgqw7ielERLlQFglmotuIO6C+/U+wZ8pHIXcwanqCtZdgh0GixTC/d2XssgeriQZP44cjTrpBGY6an8s7u0D2dErwmejZfwTOEguBZYApITy9b5cUFkAyZqfP6MVssDeb2izM+2r2GNP9SRAFxOv2EoDg1ZpLvxJZA=,iv:r7IKKP/dhyVKiOMi10/QeSRSvTS8fwktxDQo56CyGfg=,tag:L5NYPX3jY3c+KdYje65i7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
