---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age16vp92fun2zv3qqqjt0rdnz4d45s2nlgr5eqvsphypcvwnugl7gcqcemu6m"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age16vp92fun2zv3qqqjt0rdnz4d45s2nlgr5eqvsphypcvwnugl7gcqcemu6m"
stores:
  yaml:
    indent: 2
