# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:4GvGT3LCqAVWUo80lozcFyzshgtQo7FfY7lVmDYq8ZlV8QoLAxe4gRnRPu78F6L+dmOecb89ye/xUuBxNOKLsGUGv8MhybNnPQtTpfWFhE2pVhjQ7MK45yy46BmbB+tudzC8GH9V3wGMjmyci/VqtCQJNEMBckUCOaDin5bTTjYAA2M=,iv:XzJ1uTb0GXPociCLeaup9xxK9+vNYmGlSt+rVKDbV74=,tag:VEs7yF3Cv/jLILAZhEHMUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf47ye98a02dx7tc0vzqg27uzphdkqrm67fxwkq92yynylr4pp5s8knxug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubEhlNHFUZFZsdEJQcVdJ
            OXN0UXNtdDkxYXFQWmI1Lys5L2hwWVF5VlJBCk94eU0rZEkxamQ0dHFHdmpLZ3Ev
            RnU2dC9LaW1ZOXBCNldCMm9aMUNtK0EKLS0tIGtCS1ppWmJ1Z2NLRnRESkRzMVNF
            bEVIMEw4QlNwMWpQVXNvN3NsOW9lL28KxT9jzW9QiQzi6K9tD0nFAHB6uKx2bBA2
            lbZ3aXdk8DYLhnoRZxgjqwg1FiWiGKp6gg7L0AFQJ5Du/b9T12YvWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-31T12:27:33Z"
    mac: ENC[AES256_GCM,data:n4j1VXm/vULzU0zFM9lU/8GUJTg6wMpChsX19wRMdbhf2OmKP1yyajBhJt1LbwfEb+XE1IC2OA7nEkJmEA5LSESSftiJpm3Cvrf4sGHKX+DnEoIV82vL37lJIyzNIc8OB6KOVc4hTcs/ye3Ym/kCw4hDh9WiKo4cEbBRuXApUrk=,iv:jCQBJWhziUInobmePUZe9IUJEQ1JnQG8lvHHFAiNzWA=,tag:yIaWTDkY6GTb9EnR9xLRyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
