# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:KX0+p/Llbvu2FvUydMW+ia71rpspurMqlfaqIUc68UtcEvm/Q0KNr5FZuSoLaLK6D66UpLNwNXrUFrrGsnvRjdfI2Kuzmm1qpsAY99jp93NZOiTLXjyIbsY7m5sQEfhjFoXBbrTEKyzRU2/lhP5dHulWMraQm1K78ApyRQ==,iv:L3rfSjuSMXUX/c91TT7FM98cXvC4u/aPGpSWlU9Idz0=,tag:ia3ktd9m4wfoeC8T1nOA3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf47ye98a02dx7tc0vzqg27uzphdkqrm67fxwkq92yynylr4pp5s8knxug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubEhlNHFUZFZsdEJQcVdJ
            OXN0UXNtdDkxYXFQWmI1Lys5L2hwWVF5VlJBCk94eU0rZEkxamQ0dHFHdmpLZ3Ev
            RnU2dC9LaW1ZOXBCNldCMm9aMUNtK0EKLS0tIGtCS1ppWmJ1Z2NLRnRESkRzMVNF
            bEVIMEw4QlNwMWpQVXNvN3NsOW9lL28KxT9jzW9QiQzi6K9tD0nFAHB6uKx2bBA2
            lbZ3aXdk8DYLhnoRZxgjqwg1FiWiGKp6gg7L0AFQJ5Du/b9T12YvWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-31T12:36:50Z"
    mac: ENC[AES256_GCM,data:jSw/TRayqVeOBSPL6vEJUBT2v8EuRG/A6m+ZNTMQwowtAmeMO666D1U38Oj/H8mEZCvHIJPDvDdHCi0t15qWfRR0wQWEFGwHL4SW80kpZGT5DAzZ5NZBrBhkg7riTuI2IDy3OZJO0gvw7Rhl6jQkNQsm5IczejPKlMy25j+dBVs=,iv:hlCdvPAva0DdOac+DVia2XV7JpWPltPR8K//4k5Vrwg=,tag:bDsBFs4b9jXVZGC0HpPauA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
