# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:lhEK13AeUIaJftJk/ZQPX9wiCg51abrVDnJs5RK1MIIa835f2MKrbvr68Ay3ilFmcaIWLec7nXETEAzsSEIGytycupl+ZsI330XejD4bEhAtPDvJAQFLcK8PjJfrmwdLsICN7Kcua8lZaXrgBoG3rlsh6SVBOyhaTZOpreOaKmFPNF7AOF5c1MtXtfoVysE=,iv:JozyhhgkgAyBOPY17NiYTf0tiss/+BN1hpfWsTjzcSw=,tag:ARgnEq0mrtWiGYi51hlRkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf47ye98a02dx7tc0vzqg27uzphdkqrm67fxwkq92yynylr4pp5s8knxug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubEhlNHFUZFZsdEJQcVdJ
            OXN0UXNtdDkxYXFQWmI1Lys5L2hwWVF5VlJBCk94eU0rZEkxamQ0dHFHdmpLZ3Ev
            RnU2dC9LaW1ZOXBCNldCMm9aMUNtK0EKLS0tIGtCS1ppWmJ1Z2NLRnRESkRzMVNF
            bEVIMEw4QlNwMWpQVXNvN3NsOW9lL28KxT9jzW9QiQzi6K9tD0nFAHB6uKx2bBA2
            lbZ3aXdk8DYLhnoRZxgjqwg1FiWiGKp6gg7L0AFQJ5Du/b9T12YvWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-31T16:17:27Z"
    mac: ENC[AES256_GCM,data:droz9E4ya7apkjuMkq6cM6hGyQ78GKS5OBuOF79hA4vSK5l73TnMmEUBiTK+qU868fqKd99CiDgK1ZHtwEZsPwcpzy9i2USHsu+VE8laeLTg1LPhYpcHTl1IsaztquMXIVIxNiScfiF30MN5pPzfUhdPZOjEIbklouVP+Ppyr6k=,iv:K/2cfW4+Fgm5YidEswa6NcdcJubh1VJMMSUPW7bReDI=,tag:pXGIBlRLUfUpka9UbwiVdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
