---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-ceph-bucket
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ceph-block
