apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:F8qGQ8t2vDVi9RpPxEL6BvOY9ei7CQsEzFvhQM5hUWshHW1CxiTtRA==,iv:YwrUlsM+TvE0tNDld7HAsid65wwCXE515voCGtvf+i0=,tag:rvlLCHTiWZcKgNrHGNCoMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15f0yq8uvrva2hpd6grn489knhvkarj6g9xfdgyrh8mdajuq53q2q4a3uq3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3by9MV1AyWGlVZUkrWHBT
            TjNZTVYvWEJsRGh5ME9JODVYOUk1V0liTW1JCm5veEhLSkJ2UDBqOVdNb1BKdzBY
            c3k0WHRhR3pzQWdwVlFMTFRqRmdtOTQKLS0tIDN3T2FLeGZ2TXl2Z3JZSTZnb0pX
            UFFkZFdueFBqOXczQ3M4RGNhYTFKdEkKQXoHxiHuchIOheQwFPlC6Tqg6zgBNuSH
            WfDKq+1enpSjv726LyHyIbNRHwnOSDgtVrRpcgSlakT8t0ZhTWQQmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-16T09:48:37Z"
    mac: ENC[AES256_GCM,data:gACFbrbjCYktk7I5+6SgtUTcy5WuRV3JVWXsQweRKjoDbQ2VudBQwDjH6PZMIR9ZIJkuT0YdCJUu+MWX1PKZRM6zpj4Qmyxp9HkGt6gRlMwsvclVfAReqUVC2UD33P/udxoXWypSiI/6ri88KF18rrMz1IxBdM3uhWfenVr2DiY=,iv:/OcqNyl/cMvTZYhf/kwSsFIXKMldEep/msMMRmOw3e8=,tag:Vp99bNfJgT3J8O4OFr0CIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
