# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:DqscRdmlh8UNi1f+5JM5QnO/nVbdzBgOJ3pEAnFTDa0=,iv:1Z8md/JAMzsit41fktTqEJrVdzGv5oXM8eUnAanjfW8=,tag:O2wVAtllRvhor1P/hkyUqg==,type:str]
sops:
  age:
    - recipient: age16vp92fun2zv3qqqjt0rdnz4d45s2nlgr5eqvsphypcvwnugl7gcqcemu6m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcWdGNjNVSTJZQVMzK3BM
        OUxSM2RmYUUyYldiS2VwdTVBZFJONE95Vm13CmZWME5KejlBaDkzaUFQM3pkT1Ar
        QjBUdGFtNGJmSVFaSGQ4b0ZlU0lZamcKLS0tIGY1SU45N3RNc1pySDRLZ3F5dGYv
        TTRHT0YzYnBxRDdUTjVLMU93MXloc3cKZxQ4fv2nEZz3Keg9E9ffn+BXg+tN3gor
        dcyQF/y+EwVWCD4J6IU1o9h75x7aky1QBG6SxOj9x7g2lM7Cpl3ejA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-11T19:39:39Z"
  mac: ENC[AES256_GCM,data:x7GcdcHpQ20jtyOjskvkJKprYaJOb3FJSo/DwifZkLoqBE7m+ho8nP90CpwJQGaIFJ7f72qxFByNYBusAerISwlZFHjB3sEk0rZDXnX31gVvZx0X9jL4LOynjkoFu77ajYs+5NHfJNtv0HEdG2w0ETlOEt14ABsL+91/+zJj8w0=,iv:nWhagCoK4waD9lpiGlHx+V1czVt6XtV/xme9ZwJA2us=,tag:laJtIpCWvS4YYjByGHrTNQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
