---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-postgresql-pvc
  namespace: collab
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

  storageClassName: ceph-block

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: collab
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 30Gi

  storageClassName: ceph-block
