apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:4og9nIEgCdloE3Wr3nK3Zjh84DkhjpU7yxB/IbIMsyJWskhFXQ==,iv:SkblIysAeQrAhVAgKnKhl5xUwacUGPdzuPK+Si0kUDc=,tag:Sj50KB5FUKkmKb4SBPAxqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15f0yq8uvrva2hpd6grn489knhvkarj6g9xfdgyrh8mdajuq53q2q4a3uq3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMDRhVjR1TEJxZnhHTm43
            aThSdG1iTVc4T2VjVWxIbEpFT2NnZ1pHdWlnCkVHQ1llYjRONVhvbDlmVzJVcGRa
            VEF3UWlXbVJYTmlPeHo1YmlJeEVmQVUKLS0tIHFKVGpRdWJTSk14U1hmS09xTjhC
            N1N3amVhOHlUYUo5ZjQxM3pFRG4veE0KnLNOIe91nXtzyKjdq/eLIZ/JG6wevHIX
            zmbh2dicxplKiq2/CP5HpOIO59hVtlQ3MeO4yWA8/vtoy1Psd0NBKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-16T09:48:36Z"
    mac: ENC[AES256_GCM,data:hUfh1SlNmzKTauUjoBakSn7szWRGmqN3r6App2AgXQVG4eXiRUODGK45vUatQNB0Qz5R8fHKv13818MJX/A69l6x4IAY4HLyZGRGQOAnQ9E9+vifGZwnVnaPQKWzCUW828Sd6yhPcO4mSxHYYPu8Hrq72Wk1CCfrYj1/LfYyTxk=,iv:r/iT9bRsF0SYW98KL3Z5ele5Ruq0Eo8B/rVPhZNSe30=,tag:addqFyIuZKnNaBFVjd2tMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
