apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:QO4Vxj1OCcJhdes=,iv:jAgPnl0WAaUaK4QJ0UmcnNqKusXfbeU4gcGjTyO1WPc=,tag:KtZB0YSrHeuLVn+qLhzGmg==,type:str]
    api-key: ENC[AES256_GCM,data:njfPCZW1oa+x0K0XvqnnGkQqoLi/kEhw+zBamHqdwazIrr1pwQ==,iv:yp3wgRjQp2pyP6JVvoB1M83LpsDLbofuEweRbCTL25I=,tag:4QqpgnqwzL6uw9GQWtORFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15f0yq8uvrva2hpd6grn489knhvkarj6g9xfdgyrh8mdajuq53q2q4a3uq3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaK0x3d3RYWXhaTlZZaVR0
            UlgzVVVCOFk0V2twK2JIcENNK0F2QlFMT2lnCkZUeVZmWXdvYUxqMFZ0ZkdsaUJh
            bGdsS2czNndzdk90TkNpQWoyNWFubEkKLS0tIEVDbjA5Q1JWNWliK1c2aE5PckFx
            RjZDOWI2RjgxeCsrUXZuR21HaytEaFkK5nySdGpLEbunJnrxNksT0C4WigcHtyOk
            icW7u6KC/DZkAyXka5evfFyP8kV3vDo/5fi7ZyMdXAhGgLLUZwzfnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-16T09:48:36Z"
    mac: ENC[AES256_GCM,data:mu/Oe4GbHoYcUqEhB/zap8YnRnlNKAfiMRnSwfz4WPul6dnQ+doml7vIWq+3kiRmcKlzNuPZBCaUJOPFChfLP8PfNs9icvbvdAG1UpudM9bhK0sI29cWu/CLSBHfWsQ3eiFFq9dCRm38L/1Z7soaXyUX8D5CyiCrcC3d9YB0m6w=,iv:Iotelf392yLtkJG1cUGhRCCwtVjZsjblIBsyOHgEYSY=,tag:qwfqMQ7bj++p2z60n6HtSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
