# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: storage
type: Opaque
stringData:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:rz1vXL0T0Mw=,iv:0fdOhyKtnNl9mMERrVUTjr6YdXwHnHoYDt6F3BZsYmE=,tag:EYcBwcTXM6/AJO05xFfpgQ==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:C27TgPc=,iv:XYspjCiSy9LgGCy2uAbpzlb1ADJcOcQFQ5axAckFgbM=,tag:T+KMWo7p9p1pt3JOuwL/2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf47ye98a02dx7tc0vzqg27uzphdkqrm67fxwkq92yynylr4pp5s8knxug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsa1NxeDZlVmdIS3Qyb2N4
            dGtQZHFQMEpXQ1VHV1BSaDNjSU82elNvcW4wClV2cDN1VmlENkFNZXpjWmRnSDVz
            bnNNT3VaUVh2VnhkZUViTS9FQkUvZDAKLS0tIDFnczQ3NVZyMVgrWm9iNDZNOEVE
            Z0xCcll5Q0pMN242RzNPcG9PYmxJRlUKI0zsPGEjqaaV/R4XdMRYbgGEoxG1ODE1
            kdKLtgSkI/B5URKxK+7+Hpj9gp7ueyUBh/OpO7ICgZoD7I141XS+Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-30T16:19:14Z"
    mac: ENC[AES256_GCM,data:P/Xxhbp5hTRaWyHW3D4pE8EABQ8S8HDzwkHkOnTxvnTo9JSZE8rHAKxSBZUidBWuMgqIZY+r0G2Nch5GHhVqNYfig1BLa+A9JuN7L7bnkSVQIJmuUKpwG5rNqMKW9Qf7RFvEKWCLwqN+oOVoHnorYC2mdDKVe8ZrQKzgUJVI6Q4=,iv:RWpPTo2pNgtndOPDtyVLu29qMJ//kTSwNbkfihoKkR4=,tag:ngqKDNDWbJUX/J16A6tddQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
