# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: k10-minio-secret
    namespace: kasten-io
type: secrets.kanister.io/aws
stringData:
    aws_access_key_id: ENC[AES256_GCM,data:NUnwsx9PV4fhjotKRpfUcA==,iv:iQb6G4t52qTsmT2Ljt5Rrx+7zS1d1zpYOkyHoZCuvVs=,tag:DY9cdzT7IGaVgHTC5K+hTw==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:uFWdI6sMdcqWeZr6dx4RkA==,iv:J3xC7Ujdwl6OCsQK74zERDrBz23cahU+cOdxNUkj0pE=,tag:jSHk1aJwo9lGIeUcrKZ5ZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf47ye98a02dx7tc0vzqg27uzphdkqrm67fxwkq92yynylr4pp5s8knxug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdkYxRkRkUkFQZ0pSaTBs
            VFQ0ekViZ2txTjNoNnVlU3lDODNPeWJtcW5FCitpczIySWpEaFoxR3BiMW5JZjVB
            amdXSEMyRitrc2pwQUdDVXduSnBBMW8KLS0tIDc0MDN5eG1sQ2MzeEVzY3JMWGRq
            ZWQ0QnZ5RjJBZU9pUXozbTdKajN3d0EKgzVFnxO2+hg89zNW99iMnQbuSbTkaIup
            1Y6x/wSfC2SOReWcWaZJTIBb+mguh3SjZMLCyomjjrrpDUHlnC+4kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-03T14:35:41Z"
    mac: ENC[AES256_GCM,data:UzLWfWD350Xv66/FjMb0fzmOBIxwATyFCUlO31kxqdSxAQ/1V1tGvFUtotnQP6sUDj/MVX/Ticy70s/E5X+85GSlWadWPmV2A6GJ/OLdP4aq1LMimVpVy82DPlWL5sblGTMqZs9j1G1vHpTFymHKZNsJdAceHYLSlmBfX8EolWM=,iv:FEjKQRVjVk27w6So7iw6n92msccqU9UBZ8p6jvj06tg=,tag:SSSVholiT5T8nkI3qMDS5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
