# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:A/viDSkmSPhOmQ==,iv:yherx9iXxnl6ADiol+QHqXDyMr8Fuyl2FNQkClCXPwo=,tag:xhLyv0FTyEj7GCzGMWcgVQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:tywcM4W99oQQtvo=,iv:nHv2kA6uB8RctjxrlYb7WV0+AkfQb/URHkLrGpphYYM=,tag:7Ycg4CkpV1LMJKnJ/bqPlg==,type:str]
    SECRET_PGADMIN_EMAIL: ENC[AES256_GCM,data:f6d4cI/+Xmud4lg=,iv:bVf5Bo4pqoMLHYy7o8TDdZK1VIT8yAj+aHJvwOHl9+k=,tag:mN5A6w9vXMSP1rrDpjn5ug==,type:str]
    SECRET_PGADMIN_PASSWORD: ENC[AES256_GCM,data:Xm6eXznAvdI=,iv:NZqA1Mm/8CO32KFusxw8j8RHWaC1I5o4E5BniGAF3Oo=,tag:6LPC4aHyUIVRgyC3DNK8qA==,type:str]
    SECRET_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:E3KZpWYKKm0=,iv:x93oJZuvoyYTQC3GzcZBsOdWuf26KpcZTIHMyyeHz3U=,tag:NmwVksvQzCXCyBQBIA+jAQ==,type:str]
    SECRET_NEXTCLOUD_POSTGRES_PASSWORD: ENC[AES256_GCM,data:quXh10ucZig=,iv:mo7HO7KamPJQ3nFzbaL7WEa0lHs0PacUxmE9h97E2+8=,tag:MjsU3CcSpbbZuYs6ux5B/g==,type:str]
    SECRET_NEXTCLOUD_POSTGRES_USER: ENC[AES256_GCM,data:hmu3WbiQWOU=,iv:jOZFRL7OkKxB5bKxUqtWV8AsSIZ5DbOwmNJJ4l27pV8=,tag:RuORG1zwWR/0WONu54IQXA==,type:str]
    SECRET_NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:X9I9omo=,iv:IL4lKqw/C6NHKYpWyh1vdV+oZr126GkiBe6FV8wePPc=,tag:2MR4nRNZIpZ31lbgb9M2Mw==,type:str]
    SECRET_NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:7S7k4Qi/8M4=,iv:5GIzJJ+rhvEUaxWx8PLwN1v8fmAhBd93AorfDv5IvIk=,tag:ZKBKF5bYhZKkZNekFzBNKw==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:cNBhnk97AvY=,iv:7FjlifdSV1dKgq5vIHfyJM+JXHvGUAsr8nR8XL3dcsA=,tag:+aU+mC7CQ9KfsXyAElwnZw==,type:str]
    SECRET_PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:1bfcxrIRXAY=,iv:rzA9GAiDmaXO04ITGtXjuw+WPEFGVp7mxV6KxEzx4qs=,tag:UbjQO8jgd9wc4M9pXKpl8w==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:d7LlKK5a05E=,iv:EFsuQ9InoQFoOChifs9mL78jHP0p0dcpN9BLeka+dGU=,tag:5LgOmsD2tGvMYgeGnP/jgw==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:0tlNgLyaJPcraeeEQl5lEFybe4vOQJmnFQX0rrlS8uLXwUmrJ9PvbE38/45gPttuWLrVfZKk7Cchd/sFUfM7eRLEZswEfrIKablQc9dfgWFwXafQZiy6SjQkqyz8ZLDR39kx4hTCQph4ppSYOsWO5AUPkoYxka4N,iv:8sfF4NMZ4N97MmMjyROMJkfdNu9OYAssOGTN1AFq2/Y=,tag:trbBsnok39eVNEBE/SgOcQ==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:iaxuu8Z6KEC26s6Z0HsRpw==,iv:wOOUqzlXS9E82D20CrxAk4SD7T1yZq+xTsZlLdnMFvo=,tag:iOot/5I9CznQiJzoBVmqCA==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:kbXtvao589x3gNFP2yxagg==,iv:GJN3w4IpPyWcvuUeghPcLN/L+Qjqg8HcmkJNJDEFd4U=,tag:6wCaWFn/61rPBB0p8VkW2Q==,type:str]
    SECRET_VIKUNJA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:2KUYdXP9yS8=,iv:LG6CToDuJO15V0veK7nowCg/mIzeErYPhw3UM+/z7OY=,tag:0lVlFxx4m7scJ1jHPUpDTQ==,type:str]
    SECRET_VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:FP5KsVzxqnM=,iv:3dqMayB6kElfYuREdyBNiTe/qgOWtzn6CieNMVf0jRc=,tag:1PMMtQuDIEXcdH+BH0oq9g==,type:str]
    SECRET_VIKUNJA_POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:8bNiLVwrEQo=,iv:Op75rDF8Kha1iHyNKUo6bB10KqWSxJQqGSbxs1Ymb3E=,tag:cGn57vzKf9gDpOUuQnuN+g==,type:str]
    SECRET_JOPLIN_POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:1cQRWX2N5xo=,iv:Ykbn/zNx2jAIQk3hidt2PMa71uWuYfXbc2/3t0K7eX8=,tag:4pWTkVjS5J4F0F6DuzynSQ==,type:str]
    SECRET_JOPLIN_POSTGRES_PASSWORD: ENC[AES256_GCM,data:WrN8qEnwDEk=,iv:dxiYv+wOuWI2eHiHKxAxzSPw0/dR1UEaXo481u0a4d4=,tag:Lwdz5/GjIweQFfS2k6HcAQ==,type:str]
    SECRET_PAPERLESS_POSTGRES_USER: ENC[AES256_GCM,data:IIs+4FMaX2c=,iv:5xMiEW72M++KwbtaApzEaf7eMJKUKNUeDHuUnljl31c=,tag:AX2kCroyQLQ6u2pu/zkbLw==,type:str]
    SECRET_PAPERLESS_POSTGRES_PASSWORD: ENC[AES256_GCM,data:btRIfCks+/k=,iv:9QjxhsoLwQkx8gdJ9PFwplOwSwjiTdhfEqav/uWlUDo=,tag:KXRdTsvoaUShJiH/zUSOyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf47ye98a02dx7tc0vzqg27uzphdkqrm67fxwkq92yynylr4pp5s8knxug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MkxIcGxVSDBnVlErajJW
            WGhCTHUzQzllMElQczgvNHQvTHN4blhZNVI0CndTSGR5Y0xTcS85bGhjMmJvWGF6
            Rld6ZDNDMzVDRittQllOK0VBT3Y5OVkKLS0tIFFxWG91TDk3WkxIYjRwbWJsSUxl
            ZjlBZjRXejJUVjFkRWJaaEo2YkJDbFEKwA/Ded8gsVW+x7VXR7sFOOf2thW3tLzL
            o0303sTBi8oHIPeu/2tuh3fYyNOIl9CDQNyzzIYHhuDrZ+Tzeu4L6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-04T20:11:13Z"
    mac: ENC[AES256_GCM,data:6mj/0SyT7keMITmRRUiMfU4FJkVo1EqtpBrul4/FbGXRy726LeYUcJ5OXTnD9of4b2XjVR/tihHqhXDHkuiON64CdkHSW6nN4iSyG9cPhaRQ151TvtlI0ckSWNoH3XQ8VEq3JpDz4THLlQviyuWQrzTG8FFF6FHMmQlo3yitq+Q=,iv:6/YQ3NV2SU96mk5mfuC/MPw6IBW73+RSJq/0krjv6Cw=,tag:kAb9jg03MdQAIBzppBuvxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
