# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:A/viDSkmSPhOmQ==,iv:yherx9iXxnl6ADiol+QHqXDyMr8Fuyl2FNQkClCXPwo=,tag:xhLyv0FTyEj7GCzGMWcgVQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:tywcM4W99oQQtvo=,iv:nHv2kA6uB8RctjxrlYb7WV0+AkfQb/URHkLrGpphYYM=,tag:7Ycg4CkpV1LMJKnJ/bqPlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf47ye98a02dx7tc0vzqg27uzphdkqrm67fxwkq92yynylr4pp5s8knxug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MkxIcGxVSDBnVlErajJW
            WGhCTHUzQzllMElQczgvNHQvTHN4blhZNVI0CndTSGR5Y0xTcS85bGhjMmJvWGF6
            Rld6ZDNDMzVDRittQllOK0VBT3Y5OVkKLS0tIFFxWG91TDk3WkxIYjRwbWJsSUxl
            ZjlBZjRXejJUVjFkRWJaaEo2YkJDbFEKwA/Ded8gsVW+x7VXR7sFOOf2thW3tLzL
            o0303sTBi8oHIPeu/2tuh3fYyNOIl9CDQNyzzIYHhuDrZ+Tzeu4L6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-27T16:55:34Z"
    mac: ENC[AES256_GCM,data:32zxWeesAClytNrxn7z6kWvTNNNctx8RyM2uSLgP2Cx0Xo3KTVEf1hs2LtHfkAwqchtzIKH2fHKWYou6zX0yJPXiGxRn0CS7bJX64sfBvgcxLKapHpH1nBjtJ8uPr8185eRPedH4M3vEYGEAN0eFDUI/cm1TFW1c5+VgmMfJ52g=,iv:OpY8aoKxIePSzyZd25WPNLzKCeq3XZYeIGGRwn5aL8c=,tag:OnTSPGRmjYGgINWHJp3wMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
