# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:A/viDSkmSPhOmQ==,iv:yherx9iXxnl6ADiol+QHqXDyMr8Fuyl2FNQkClCXPwo=,tag:xhLyv0FTyEj7GCzGMWcgVQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:tywcM4W99oQQtvo=,iv:nHv2kA6uB8RctjxrlYb7WV0+AkfQb/URHkLrGpphYYM=,tag:7Ycg4CkpV1LMJKnJ/bqPlg==,type:str]
    SECRET_PGADMIN_EMAIL: ENC[AES256_GCM,data:f6d4cI/+Xmud4lg=,iv:bVf5Bo4pqoMLHYy7o8TDdZK1VIT8yAj+aHJvwOHl9+k=,tag:mN5A6w9vXMSP1rrDpjn5ug==,type:str]
    SECRET_PGADMIN_PASSWORD: ENC[AES256_GCM,data:Xm6eXznAvdI=,iv:NZqA1Mm/8CO32KFusxw8j8RHWaC1I5o4E5BniGAF3Oo=,tag:6LPC4aHyUIVRgyC3DNK8qA==,type:str]
    SECRET_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:E3KZpWYKKm0=,iv:x93oJZuvoyYTQC3GzcZBsOdWuf26KpcZTIHMyyeHz3U=,tag:NmwVksvQzCXCyBQBIA+jAQ==,type:str]
    SECRET_NEXTCLOUD_POSTGRES_PASSWORD: ENC[AES256_GCM,data:quXh10ucZig=,iv:mo7HO7KamPJQ3nFzbaL7WEa0lHs0PacUxmE9h97E2+8=,tag:MjsU3CcSpbbZuYs6ux5B/g==,type:str]
    SECRET_NEXTCLOUD_POSTGRES_USER: ENC[AES256_GCM,data:hmu3WbiQWOU=,iv:jOZFRL7OkKxB5bKxUqtWV8AsSIZ5DbOwmNJJ4l27pV8=,tag:RuORG1zwWR/0WONu54IQXA==,type:str]
    SECRET_NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:X9I9omo=,iv:IL4lKqw/C6NHKYpWyh1vdV+oZr126GkiBe6FV8wePPc=,tag:2MR4nRNZIpZ31lbgb9M2Mw==,type:str]
    SECRET_NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:7S7k4Qi/8M4=,iv:5GIzJJ+rhvEUaxWx8PLwN1v8fmAhBd93AorfDv5IvIk=,tag:ZKBKF5bYhZKkZNekFzBNKw==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:cNBhnk97AvY=,iv:7FjlifdSV1dKgq5vIHfyJM+JXHvGUAsr8nR8XL3dcsA=,tag:+aU+mC7CQ9KfsXyAElwnZw==,type:str]
    PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:qAkI5i803tg=,iv:HeFTFtX3vx1c2jNbtK0LSb6fiIvWHe70bmioUQLgZPk=,tag:rvqVFKNFX5FjLNnob49W9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf47ye98a02dx7tc0vzqg27uzphdkqrm67fxwkq92yynylr4pp5s8knxug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MkxIcGxVSDBnVlErajJW
            WGhCTHUzQzllMElQczgvNHQvTHN4blhZNVI0CndTSGR5Y0xTcS85bGhjMmJvWGF6
            Rld6ZDNDMzVDRittQllOK0VBT3Y5OVkKLS0tIFFxWG91TDk3WkxIYjRwbWJsSUxl
            ZjlBZjRXejJUVjFkRWJaaEo2YkJDbFEKwA/Ded8gsVW+x7VXR7sFOOf2thW3tLzL
            o0303sTBi8oHIPeu/2tuh3fYyNOIl9CDQNyzzIYHhuDrZ+Tzeu4L6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-28T07:41:26Z"
    mac: ENC[AES256_GCM,data:RkGxENquaYffZVo/68yVYPAUerEaomOAk6JeBWEzRIJha+Xjx6C1AK7C8TqEnM+5P1sy9SXh6hI1Jxji85czfZiAMjbdrAC2OzaPjsPACrf4CHotEOJO9vJugnofVdLxee+wYk8kMKaN9YRAJ+++SbgCBA6eNr9O11L9dwPRK30=,iv:BRKs1J4DLghYRxPxK2bel/4QqmcKtQ36ADk/VEV9xDA=,tag:3EChuOVD3OTlUi6nzbWumQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
