---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/linuxserver/qbittorrent
      tag: release-4.4.0-ls168
    env:
      TZ: "Asia/Dubai"
      DOCKER_MODS: "linuxserver/qbittorrent|ghcr.io/gilbn/theme.park:qbittorrent"
      TP_THEME: "dracula"
    settings:
      automaticPortSetup: false
    service:
      main:
        ports:
          http:
            port: 8080
      bittorrent:
        enabled: true
        type: LoadBalancer
        # loadBalancerIP: 192.168.2.62
        externalIPs:
          - "${SVC_QBITTORRENT_ADDR}"
        ports:
          bittorrent:
            enabled: true
            port: 50413
            protocol: TCP
            targetPort: 50413
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-download"
        hosts:
          - host: &host "qb.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: qbittorrent-tls
            hosts:
              - *host
    metrics:
      enabled: true
      exporter:
        image:
          repository: ghcr.io/k8s-at-home/prometheus-qbittorrent-exporter
          tag: v1.2.0
      serviceMonitor:
        interval: 1m
        scrapeTimeout: 10s
      prometheusRule:
        enabled: true
    podSecurityContext:
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-v2
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADD}"
            path: /mnt/bear/media
        mountPath: /media
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 3000Mi
