---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  releaseName: qbittorrent
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/qbittorrent
      tag: release-4.4.0-ls168

    settings:
      automaticPortSetup: false

    podAnnotations:
      setGateway: "true"

    hostname: qbittorrent

    env:
      TZ: "Asia/Dubai"
      DOCKER_MODS: "linuxserver/qbittorrent|ghcr.io/gilbn/theme.park:qbittorrent"
      TP_THEME: "dracula"
    service:
      main:
        ports:
          http:
            port: 8080
      bittorrent:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_QBITTORRENT_ADDR}"
        ports:
          bittorrent:
            enabled: true
            port: 50413
            protocol: TCP
            targetPort: 50413
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-download"
        hosts:
          - host: "qb.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "qb.${SECRET_DOMAIN}"
            secretName: tls.qb

    podSecurityContext:
      supplementalGroups:
        - 100

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-v2

      nfs-nas-media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADD}"
            path: /mnt/bear/media
        mountPath: /media
        readOnly: false

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 3000Mi

    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2m

    # additionalContainers:
    #   - name: exporter
    #     image: esanchezm/prometheus-qbittorrent-exporter:latest
    #     imagePullPolicy: IfNotPresent
    #     env:
    #       - name: QBITTORRENT_HOST
    #         value: "http://localhost"
    #       - name: QBITTORRENT_PORT
    #         value: "8080"
    #       # - name: QBITTORRENT_USER
    #       #   value: "${SECRET_QB_USER}"
    #       # - name: QBITTORRENT_PASS
    #       #   value: "${SECRET_QB_PASSWORD}"
    #       - name: EXPORTER_PORT
    #         value: "9022"
    #       - name: EXPORTER_LOG_LEVEL
    #         value: "INFO"
    #       - name: METRICS_PREFIX
    #         value: "qbittorrent"
    #     ports:
    #       - name: metrics
    #         containerPort: 9022
    # nodeSelector:
    #   node-role.kubernetes.io/worker: "true"
