apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:cvumfUi5RFgmN+tp1L3wzRd7wQUZauCQZ6KFPZ7oVe7Vb78aL8FpP3+/gCGHeyHERMBtxbEIiyne8Vqs,iv:ZK8593B6J6sz92k7ZQUOIpNc9ClIg0J56RUwpKHtMMI=,tag:ecjokflB4tvEsopDcSR6WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15f0yq8uvrva2hpd6grn489knhvkarj6g9xfdgyrh8mdajuq53q2q4a3uq3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUm1DYVp1NkNYeUlDbGRp
            YUhiK1pOZ0Q4MHAyWnJvSDRKcXkrdUJaV1JzClpkZTVTTUVEQjNXWGtNRmptNUxJ
            VkgxTkhaR2NUeWxJaDczUWpDWlEvZFkKLS0tIDcxVFZnV3lkeUVOemhYMmszTDdr
            eDRicUdKd2hadlNGSzhpUmF1czBVUW8Khw8pUbTrCpEGAIMRaUbnGeb0URk6zWwh
            U2YEV3OOb4vghUGcisFdqFuVjdWFVAFk45J5Utw9EwFo6AmNgEHOyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-16T09:48:39Z"
    mac: ENC[AES256_GCM,data:/7H6TMZ7EsUwlIWholVO1rG8g7YfPlOa2EkdbAsR+TP307PRnFOpa9F6eRGFFAAsGmrhwhMsjMalnciwELEQDwttjDA4Pyo1+/mUthWThcJf48QeeUUsXTWDCVmjCyGrKKzsn173eeh2FoSdcw7/2vx+DUFbgmtlso0pheeuiy8=,iv:SA+FikITYwfFN0XF/4YBBoxuuaVQn8XUALfc0588Pbc=,tag:/JW+BDDajwywCNNIKwu2iA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
