apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LffE8FBDx/74c+M=,iv:nJAr76YnRKhHmfAO+sBCmaG/9HuFdIkozC4N3bWfbew=,tag:sI1QGA4Eo6tjT9dA6Lvr4g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:yCAIXz/96gNbX3A=,iv:NIl99vtkz+9s+qN9SsWNIPlg/Qdf5yyFCM9JvuBtIfs=,tag:46C6bX/FZe5DO+fdz6bZcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15f0yq8uvrva2hpd6grn489knhvkarj6g9xfdgyrh8mdajuq53q2q4a3uq3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ1JheFpWdEVmaWg4bkdJ
            MkdaZjN1UnJlS0xQNDI3M0tQNWE4cUhXcDM4CkhXSVZ5N2RCN3F6RVNkUHRRTHlF
            STAyOXhncUwva29mRkUrRG0wSHBUYm8KLS0tIHJ0b3pGZ3J0OGFHOEcvOFhDTE1z
            UEtPamhvWVlLSDM0VStXWi83UlhRdDQKCkZnVxbnuy1w3DBxjip3IDtKxF1jEnq2
            kzIFEyPtJLB8Y89jQBCPfGvp3wyeiJWwkIIqQq1BcWNINTPQQGN/LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-16T09:48:36Z"
    mac: ENC[AES256_GCM,data:Im4yyR/qVz0zbfYPg/9umAupUcHz7SEIQJW8khqF+0hPdejkynGRtUO76LECKnK2qnexp3ZOBSLpm3mUEVK75FvZacy/BxBkjc8sI26IiUZBl5uP4mOmsE4LGqKvP3J89H52zT6+dvsFJVZwIm381n9oC91Oi2WpKbRauHrca1c=,iv:N4vl98LjmJI5JlLzNEtSMYK0p0Uj5HNv3hJuZEnhIHo=,tag:UDQWzqZSVfiKi0h5rL/FEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
