# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: storage
type: Opaque
stringData:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:jpIVMUJPAEM=,iv:yZAnp3bVPih7LWgfzIuOX8P6hYAoGTgiuX7dOfGEqvU=,tag:YfRkUnf2enpkesZQhdzdSA==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:vpsB2C0=,iv:mlKwdvRboXRDhbVSaG0iG+l2wF/t3T41wo/Igx/iVAo=,tag:KiwYFfBvDJVBCfVt+qkk8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf47ye98a02dx7tc0vzqg27uzphdkqrm67fxwkq92yynylr4pp5s8knxug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUUY4WTdNcXl4elljTVht
            R2x2NXRlOEN5WDZVNmd2dENaWDd6VHliOEZJCmd1cTBxU1R6R2JXcEVydElualdL
            ZkUrL3YwVlV4dEl2RTE2cHJabnkxaFkKLS0tIGViSkxoRG1zSHpwamZoVytWQThE
            OVBRU3VyQzlDVFFtMnhBOWd4eWE0SVEKHqo0qX04Wp/Demnxt9g0PeYGdIoXEKUo
            1MLr4r9yBpFBwl4/9Vs0QEBxZZaYXRxDi7sALxm+rSxZbvTRG/HXIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-30T17:15:37Z"
    mac: ENC[AES256_GCM,data:E6RRuARq5K1kJTHcBiR6xSgDiZYB5VniF69Er8ql8WZ0b3iqAbZDemxdIKzkei4nSCOLzC379iz++xQX2aKzUFVlN4EZd6l4tovc6YzL5HWtPvtygqigoTUCg3W2lERejUc84IMK/rEwKvDHBfyGgK2fl9lzZOiT5dYLQLkNM9E=,iv:a4OEGgfDMDyTC6LTf0WvQ7gY8qnSO9tUixYTbSIRCvE=,tag:Th7rBRUqb3DJvk/odNPVfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
