# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: storage
type: Opaque
stringData:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:rfcReN8ovBU=,iv:w3BOrfs7GR58CKh/wj8kK12p7YF7AY2iFF1aP5DGJ7s=,tag:Q25mW9eCRQzD409J1/bAkw==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:g2+ZIpg=,iv:1XI2OPknw1znr2fX4jWeOhh0p6G/xuw1tBQF5EcXRnQ=,tag:6rUgpMwmnxZyRomADWQ/dQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf47ye98a02dx7tc0vzqg27uzphdkqrm67fxwkq92yynylr4pp5s8knxug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMlArd1VnODFZYVZCOGFj
            bTdCTEJvRDU4VVI3MWppRnduNTNTYTF4UUZnCmMwd25SSHJFUU5BOXpQdUpjQVRK
            MWpKR0lQZ24vTm0zc3hUUVpjVElXZEEKLS0tIHJtUzJCNVdyZytWUS9JSkxNTkpN
            Vzh4REtGRit4dzI1c1QyRGZoZ1lVVmcKMtq1Uu4wiFP4DSozbG9SPgwPzXkjvOwi
            vUqVREGcsmk0v7hAZeNn56e73ud21U6DD9WovwBR3KxO7o24K5UfgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-30T18:19:37Z"
    mac: ENC[AES256_GCM,data:Z8tScFCOVdngi0QyxcD94wA7P+etHaDpCDw7ihkgIrMsuZQ/m1b48pUMw0QSCpFNBm/q1lbQg9ngf/1YNE/afuZofpmKq1NWRyB97D9k7SY+BpFRZFwPCTW4tv0gSWo1kKZqpHADhUHkyU28gNtfho47yDNutSO6IDEBU+Xm/yY=,iv:lJWItiohgftdQdy0ClUYP2Os6AuG5SgcbhZebJ9Alo8=,tag:U4o3rMZUZASKBVqTgJW6Ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
