apiVersion: v1
kind: Secret
metadata:
    name: unpackerr
    namespace: media
stringData:
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:pFKwg6D9KYJPgoc7YZ0ThlPm/9NjxR+eBIMZAt/PVb0=,iv:exUNDccq0eUabyhbkXwWF2ZE52Ap/DSvTvXM3xuBi8k=,tag:SI7b6Zdlq9EuFWsYn1przA==,type:str]
    UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:zpEWkAqMLthFzQ+2R0/BUWMbpziUXquRVBlXv2a0SJM=,iv:zejibQnESC2Vyy7/dBV0Hwn+GrGlps1P2PH73hlzF+Y=,tag:l8gWE6lJYFu2pVBQDHdJ8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf47ye98a02dx7tc0vzqg27uzphdkqrm67fxwkq92yynylr4pp5s8knxug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMWU3cUdjNGZFYzdnalVk
            Q1JCZkR5N0ovc0t5Vk02emJZcVkwZTJ2TlVvCjhwRU10NlNDVjNGNjlPOWlja0I0
            YmlRb2NiS3RnVFlUdDZyVkpiRE9ZMDgKLS0tIHNINUVzcHhlc1BldzNDV3RzdTRE
            SFdGcDZoR2tUcWQ0cVhXb0YyZnIwT00K8jfZwoHUbrj2dO8QlNg31I5QH9J2snve
            1UA7nizjacTSXwy148hVgQy8FVjPow51Q1kCV46Mmy3thVUZWimS6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-07T18:32:29Z"
    mac: ENC[AES256_GCM,data:Q9oklozTWGxm81XsaeOHH0Vq+Sk9NbQWdLefH9ya0kuS45QOEtaZcOM57fT8WoTh6jgoH68IS/WfRjk9GHRedW+l94s1W0rwTSRI4wyYvsvFMcR09lV80z30rcvBD7ZVx9esLyC9Jz9cmqbTA71ljBgzjMRkzv0RQGqBhZhcAQc=,iv:+VSHm4otIsCSQTbTqLeHBKVLwV7G9x+nWOW1CHPhd2Y=,tag:x+YtB3BoB+8JeasP5nicTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
