apiVersion: v1
kind: Secret
metadata:
    name: unpackerr
    namespace: media
stringData:
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:FZxvlOcpQvdatkzYbFQryk8ALezZY4nlm1hzNuVH+mw=,iv:DMMFyFFi9K2EHgYJuO7RzOjpIEG+Y1KiT53wHD1ypkQ=,tag:enJGlSuxoy3gssEKZKjG7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf47ye98a02dx7tc0vzqg27uzphdkqrm67fxwkq92yynylr4pp5s8knxug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMWU3cUdjNGZFYzdnalVk
            Q1JCZkR5N0ovc0t5Vk02emJZcVkwZTJ2TlVvCjhwRU10NlNDVjNGNjlPOWlja0I0
            YmlRb2NiS3RnVFlUdDZyVkpiRE9ZMDgKLS0tIHNINUVzcHhlc1BldzNDV3RzdTRE
            SFdGcDZoR2tUcWQ0cVhXb0YyZnIwT00K8jfZwoHUbrj2dO8QlNg31I5QH9J2snve
            1UA7nizjacTSXwy148hVgQy8FVjPow51Q1kCV46Mmy3thVUZWimS6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-06T18:22:19Z"
    mac: ENC[AES256_GCM,data:hi/s4e26RTHJWjiwAAu9sUM9QmJtXDOLa/ezy2Q3JI0hAvTF1qfVoQM0hq6GtCwz3G+gu4mYm0UITT1vD4Nz5p796mD3SVwSlVaAtONzoW8OaEwxGtfTI6d6p0FafPxUu9JeIZSpswAPzHXp6aEJhGZ5AqGW6zNcTXIm16LfmAk=,iv:DAH4sUx7rTLaJUlXfFNlWPUitcKwZWxcihIbhrXglOs=,tag:062awYWaI1kI2FCiBVJWMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
