apiVersion: v1
kind: Secret
metadata:
    name: unpackerr
    namespace: media
stringData:
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:pFKwg6D9KYJPgoc7YZ0ThlPm/9NjxR+eBIMZAt/PVb0=,iv:exUNDccq0eUabyhbkXwWF2ZE52Ap/DSvTvXM3xuBi8k=,tag:SI7b6Zdlq9EuFWsYn1przA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf47ye98a02dx7tc0vzqg27uzphdkqrm67fxwkq92yynylr4pp5s8knxug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMWU3cUdjNGZFYzdnalVk
            Q1JCZkR5N0ovc0t5Vk02emJZcVkwZTJ2TlVvCjhwRU10NlNDVjNGNjlPOWlja0I0
            YmlRb2NiS3RnVFlUdDZyVkpiRE9ZMDgKLS0tIHNINUVzcHhlc1BldzNDV3RzdTRE
            SFdGcDZoR2tUcWQ0cVhXb0YyZnIwT00K8jfZwoHUbrj2dO8QlNg31I5QH9J2snve
            1UA7nizjacTSXwy148hVgQy8FVjPow51Q1kCV46Mmy3thVUZWimS6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-07T05:35:10Z"
    mac: ENC[AES256_GCM,data:hWn3fg3KEwVJA14MCpGO7LjdIq04IlOLn7+an1Tch0Lsv1acjOD4EFSRK3gn9DXB/rvrjVYmrR55hZY8LLC+CuVuUfkcIUS2P0MRiCLMRB+wT1yfxUYY1xqts07cPsjAaig1C5v/zP4E6pu0Rnn7wNFWdskFJ7CgsYTjUTu73fg=,iv:t1UFdV4E5FaNdn0a2S+8xdZhVVp8fa9QfmaxGly8ScM=,tag:TQzPtZ1GZoTSCMc/iN8Irw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
