# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:E0ag7BfYg2aHFxFt7Q08bSBzK04ed6f9TPPotI6PvK7e7dH1tA==,iv:69TXnADQ3lIpKDjTtbcycTV7giXh0HRTrItVRHLcACU=,tag:T7LYSaw52L+TFpvdbsaiSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf47ye98a02dx7tc0vzqg27uzphdkqrm67fxwkq92yynylr4pp5s8knxug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUTVCMUkyU3MvemVIYk9q
            SjhmQzBZUnpOS2s5clRPdHFJYnFSRmNRV2xJClYwNnBtd1BjdHQvU3ZZVVRNNFp3
            eDVwYnlwRzR0cnBpSVBGU1NOa1RialUKLS0tIFRKeGZFVndqYlJzSVN2bnlqQlBG
            MFhSYmZ5d09MK2l3YVh4YS9IMjcwUUEK+aOp+8PehHWhidTAZl0hm9P8c89pdWO5
            fPFHCIKUoi7UvlZVqTLdJLDsRgt0iM+TOY66n21pMCELoFzDPzmVfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-27T16:55:34Z"
    mac: ENC[AES256_GCM,data:5VWc8/RbbYaMMI/4Fbasew87ItDRWNJKaWuBFyOG19fFT53xBH4FMYMLcXeq/eo9hUxAsNNy+BZBOf1/OiofPBYcyFqxK70KkuNaZ8Plr83DL1+NIZcqz6KJ/kFJMEsQwsMJ13kzTADWIyIJJ9uCdy9MiZslC5o9TShC7n6VAc8=,iv:eZb84O+sS/ZuIIJm0s7MbTBNqj171RHacjErTJpXdgA=,tag:+jMkxyvyo6zDt/YCc/z0gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
