---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ng-postgresql-pvc
  namespace: collab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-block
